"""Fourth Migration-Corrections

Revision ID: 5c35c2746827
Revises: 19c0feac9d17
Create Date: 2019-04-24 13:04:16.146162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c35c2746827'
down_revision = '19c0feac9d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('content', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('pitches', 'pitch_content')
    op.drop_column('pitches', 'pitch_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('pitch_content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'title')
    op.drop_column('pitches', 'content')
    # ### end Alembic commands ###
