"""Seventh Migration-Corrections

Revision ID: 5efcc6a51076
Revises: 1d4c0d600705
Create Date: 2019-04-25 04:37:52.677819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5efcc6a51076'
down_revision = '1d4c0d600705'
branch_labels = None
depends_on = None

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('pitches')
    op.drop_table('users')
    # ### end Alembic commands ###
